### ISSUE TITLE
Failed to load the autocomplete-elixir package

### ISSUE THREAD

**Issue by Lu-i** [iraasta/autocomplete-elixir#1]
**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.2
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v0.1.0

### Stack Trace

Failed to load the autocomplete-elixir package

```
At Cannot find module 'mime'

Error: Cannot find module 'mime'
  at Module._resolveFilename (module.js:351:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/lui/.atom/packages/autocomplete-elixir/lib/server/static.js:9:12)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/lui/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir.coffee:2:1)
  at Object.<anonymous> (/Users/lui/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:460:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:77:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
  3x -9:36.6 core:backspace (atom-text-editor.editor.mini)
  3x -9:34.3 core:confirm (atom-text-editor.editor.mini)
  3x -7:42.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack.remove)
     -0:28.6 editor:newline (atom-text-editor.editor)
 10x -0:25.9 core:backspace (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-css, v0.6.0
autocomplete-elixir, v0.1.0
autocomplete-html, v0.5.0
autocomplete-plus, v2.7.0
autocomplete-ruby, v0.0.1
elixir-cmd, v0.2.5
iex, v0.8.6
language-elixir, v0.3.4
linter-elixirc, v0.2.1
script, v2.18.0

# Dev
No dev packages
```

**Comment by iraasta** [comment]
Please try to install it by hand into the packages folder.

I'll try to fix dependencies.

**Comment by iraasta** [comment]
Please update the package to version 1.0.0 and tell me if there are still any problems.

Cheers
