### ISSUE TITLE
Uncaught TypeError: Cannot read property 'stdout' of undefined

### ISSUE THREAD

**Issue by Hades32** [iraasta/autocomplete-elixir#10]
[Enter steps to reproduce below:]

1. happens directly after installing
2. ...

**Atom Version**: 0.201.0
**System**: C415M5CB3410TQN
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.2.6

### Stack Trace

Uncaught TypeError: Cannot read property 'stdout' of undefined

```
At C:\Users\MRAUSC\.atom\packages\autocomplete-elixir\lib\alchemide\wrapper.coffee:19

TypeError: Cannot read property 'stdout' of undefined
    at Object.exports.init (C:\Users\MRAUSC\.atom\packages\autocomplete-elixir\lib\alchemide\wrapper.coffee:36:21)
    at exit (C:\Users\MRAUSC\.atom\packages\autocomplete-elixir\lib\alchemide\wrapper.coffee:27:22)
    at triggerExitCallback (C:\Users\MRAUSC\AppData\Local\atom\app-0.201.0\resources\app.asar\src\buffered-process.js:213:47)
    at ChildProcess.<anonymous> (C:\Users\MRAUSC\AppData\Local\atom\app-0.201.0\resources\app.asar\src\buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
atomatigit, v1.5.1
autocomplete-elixir, v1.2.6
go-plus, v3.3.11
language-elixir, v0.4.0

# Dev
No dev packages
```

**Comment by iraasta** [comment]
On it

**Comment by iraasta** [comment]
It's probably an effect of issue #11

**Comment by iraasta** [comment]
I don't see autocomplete-plus installed in Your packages. Are You sure You've got that installed?

**Comment by Hades32** [comment]
No, I'm new to Atom. I assumed that it did dependency resolution itself, just like any other IDE...

**Comment by iraasta** [comment]
@Hades32 
Nope. It doesn't. autocomplete-elixir is a resolver for autocomplete-plus.
Please install autocomplete-plus and it should be fine.
Hit me up if it fixed the issue :smile:

**Comment by Hades32** [comment]
Yeah, it works now! Thanks!

I'm pretty disappointed by Atom though, that it doesn't support plugin dependencies...

**Comment by iraasta** [comment]
Give them some time. It's still young.
And to be honest, easiness of writting of plugins is absolutely amazing.
They should fix MacOS and Windows integration though, beacuse I see a lot of errors on these.
Especially MacOS.
Have a good day and peace from alchemists' community :cocktail: :grinning:

**Comment by 7sharp9** [comment]
I still get this with the latest version 1.3.7

**Comment by fibric** [comment]
autocomplete-plus is installed (bundled with atom 1.0), getting this error since upgrading to 1.3.7 and 1.3.8

**Comment by iraasta** [comment]
@fibric Really? I thought I fixed potential issue in 1.3.8

**Comment by iraasta** [comment]
It is something related to failing to spawn the

**Comment by fibric** [comment]
what information from my machine do you need to find the root cause of this issue?

**Comment by iraasta** [comment]
Stack trace tells not that much here. But I guess it could help. I regret they don't send local variables with that

**Comment by iraasta** [comment]
https://discuss.atom.io/t/send-local-variables-with-stack-trace-when-sending-issue-report/18172?u=iraasta

**Comment by fibric** [comment]
```
/Users/fibric/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:31
Hide Stack Trace
TypeError: Cannot read property 'stdout' of undefined
  at Object.exports.init (/Users/fibric/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:31:19)
  at exit (/Users/fibric/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:19:53)
  at triggerExitCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)
```

**Comment by iraasta** [comment]
atom/atom/issues/6956

**Comment by wende** [comment]
Does it happen anymore?
Also I've added Troubleshooting to the README.md file
Please check out if anything works for you from there
