### ISSUE TITLE
Failed to activate the autocomplete-elixir package

### ISSUE THREAD

**Issue by TrevorS** [iraasta/autocomplete-elixir#18]
[Enter steps to reproduce below:]

1. Install `autocomplete-elixir`.
2. Set the Elixir Path to `/usr/local/bin/elixir`
3. Enable the package.

**Atom Version**: 1.0.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.3.7

### Stack Trace

Failed to activate the autocomplete-elixir package

```
At Cannot read property 'stdout' of undefined

TypeError: Cannot read property 'stdout' of undefined
  at Object.exports.init (/Users/trevor/.atom/packages/autocomplete-elixir/lib/alchemide/wrapper.coffee:25:19)
  at new RsenseClient (/Users/trevor/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:11:18)
  at new RsenseProvider (/Users/trevor/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:9:25)
  at Object.module.exports.activate (/Users/trevor/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir.coffee:13:27)
  at Package.module.exports.Package.activateNow (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
  at Package.module.exports.Package.measure (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
  at Package.module.exports.Package.activate (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:313:19
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:574:20
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Config.module.exports.Config.emitChangeEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:736:29)
  at Config.module.exports.Config.setRawValue (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:551:19)
  at Config.module.exports.Config.set (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:233:14)
  at Config.module.exports.Config.removeAtKeyPath (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/config.js:343:12)
  at Package.module.exports.Package.enable (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package.js:150:26)
  at PackageManager.module.exports.PackageManager.enablePackage (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/package-manager.js:142:14)
  at HTMLButtonElement.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-card.js:310:27)
  at HTMLButtonElement.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLButtonElement.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```

### Commands

```
     -0:40.8.0 settings-view:open (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:15 core:paste (atom-text-editor#autocomplete-elixir.elixirPath.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "wrap-guide"
    ]
  },
  "autocomplete-elixir": {
    "elixirPath": "/usr/local/bin/elixir"
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v4.1.4
autocomplete-elixir, v1.3.7
language-elixir, v0.5.1
vim-mode, v0.54.0

# Dev
No dev packages
```

**Comment by iraasta** [comment]
The path should be without elixir at the end. Just the folder to it
Any idea how could I write it less ambiguous?

**Comment by HBYoon** [comment]
Also happens in to windows 8.1. And in my case, issue has been fixed in below ways. 
[https://github.com/HBYoon/autocomplete-elixir/commit/b789da8c290fcefec028fd88a2a2cb1af3334e3f]

**Comment by HBYoon** [comment]
Also happens in to windows 8.1. In my case, issue has been fixed with below codes.

```
  ## from line 20 of lib/alchemide/wrapper.coffee
  setting = atom.config.get('autocomplete-elixir.elixirPath')
  setting = if setting == "elixir" then "" else setting
  command = path.join (setting), "elixir"
```

**Comment by iraasta** [comment]
I mean the settings instructions. Not the code

**Comment by iraasta** [comment]
I will make it work for both

**Comment by iraasta** [comment]
atom/atom/issues/6956
