### ISSUE TITLE
Failed to load the autocomplete-elixir package

### ISSUE THREAD

**Issue by theocodes** [iraasta/autocomplete-elixir#2]
[Enter steps to reproduce below:]

1. Install

**Atom Version**: 0.188.0
**System**: Mac OS X 10.10.1
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v0.1.2

### Stack Trace

Failed to load the autocomplete-elixir package

```
At dlopen(/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/pty.js/build/Release/pty.node, 1): no suitable image found.  Did find:
	/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/pty.js/build/Release/pty.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00

Error: dlopen(/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/pty.js/build/Release/pty.node, 1): no suitable image found.  Did find:
	/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/pty.js/build/Release/pty.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/pty.js/lib/pty.js:8:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/pty.js/index.js:2:18)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/erlang/erlang.js:6:11)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/autocomplete-elixir/lib/server/static.js:30:1)
  at Module._compile (module.js:475:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir.coffee:2:1)
  at Object.<anonymous> (/Users/theocodes/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir.coffee:1:1)
  at Module._compile (module.js:475:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:370:32)
  at Function.Module._load (module.js:325:12)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app/src/package.js:678:34)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:189:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:167:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app/src/package.js:181:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:383:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:460:30)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:268:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:43:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:63:47)
  at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:138:20)
  at Pipe.close (net.js:477:12)

```

### Commands

```
     -0:50.0 core:save (atom-text-editor.editor)
     -0:48.5 command-palette:toggle (atom-text-editor.editor)
  3x -0:43.4 core:move-down (atom-text-editor.editor.mini)
  2x -0:42.2 core:move-up (atom-text-editor.editor.mini)
     -0:41.9 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:41.9 core:cancel (atom-text-editor.editor.mini)
     -0:40.7 command-palette:toggle (atom-text-editor.editor)
     -0:38.3 core:confirm (atom-text-editor.editor.mini)
     -0:38.3 script:run (atom-text-editor.editor)
     -0:28.7 core:select-all (atom-text-editor.editor)
     -0:28.5 editor:delete-to-beginning-of-line (atom-text-editor.editor)
     -0:27.7 core:save (atom-text-editor.editor)
     -0:25.9 editor:newline (atom-text-editor.editor)
  3x -0:19.1 core:backspace (atom-text-editor.editor)
     -0:10.8 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v0.1.2
elixir-cmd, v0.2.5
iex, v0.8.6
language-elixir, v0.3.4
linter-elixirc, v0.2.1
minimap-git-diff, v4.1.2
script, v2.18.0

# Dev
No dev packages
```

**Comment by namxam** [comment]
Having the same issues with atom 1.190

**Comment by iraasta** [comment]
Please update to 1.0.0 and try right now.
I've changed the whole way autocompletion worked.
Now it should work on all platforms
