### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by AndreaCatalucci** [iraasta/autocomplete-elixir#4]
[Enter steps to reproduce below:]

1. created a Cat struct
2. tried to use it with default values by writing %Cat{}

**Atom Version**: 0.192.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-elixir](https://github.com/iraasta/autocomplete-elixir) package, v1.1.2

### Stack Trace

Uncaught TypeError: Cannot read property 'toUpperCase' of undefined

```
At /Users/andreacatalucci/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:39

TypeError: Cannot read property 'toUpperCase' of undefined
  at RsenseProvider.module.exports.RsenseProvider.findSuggestions (/Users/andreacatalucci/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:39:30)
  at /Users/andreacatalucci/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-provider.coffee:25:24
  at /Users/andreacatalucci/.atom/packages/autocomplete-elixir/lib/autocomplete-elixir-client.coffee:24:7
  at /Users/andreacatalucci/.atom/packages/autocomplete-elixir/lib/new/wrapper.coffee:27:5
  at Socket.fn (/Users/andreacatalucci/.atom/packages/autocomplete-elixir/lib/new/wrapper.coffee:43:7)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
     -0:07.2 core:backspace (atom-text-editor.editor.is-focused)
     -0:06.9 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "unity-ui",
      "monokai"
    ]
  },
  "autocomplete-elixir": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-elixir, v1.1.2
autocomplete-erlang, v0.2.4
autocomplete-plus, v2.11.0
autocomplete-snippets, v1.2.0
elixir-cmd, v0.2.5
iex, v0.9.2
language-elixir, v0.4.0
linter, v0.12.0
linter-elixirc, v0.2.1
monokai, v0.14.0
unity-ui, v2.0.5

# Dev
No dev packages
```

**Comment by iraasta** [comment]
Yes. The issue was with autocompletion being invoked in 0 length strings.
Fixed in 644d81ea52f7ef32a7eb341165847eb4e62be9b7
